# Generated by Django 6.1 on 2026-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('turma', models.CharField(max_length=50)),
                ('frequencia', models.FloatField()),
            ],
        ),
    ]
